Hw3 fragments
cat-in-magic-hat/MoviesLibrary pull request #3
Opened 2021-02-08 22:16 UTC by cat-in-magic-hat

2021-02-09 21:13 UTC, baidala requested changes
хороший проект. исправьте диалог и креш при повороте екрана (на всех фрагментах) 
androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.example.movieslibrary.MoviesListFragment: could not find Fragment constructor
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:538)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManagerImpl$6.instantiate(FragmentManagerImpl.java:2851)
        at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:85)
        at androidx.fragment.app.FragmentManagerImpl.restoreSaveState(FragmentManagerImpl.java:2488)
        at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:195)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:288)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
        at com.example.movieslibrary.MainActivity.onCreate(MainActivity.kt:51)

2021-02-09 21:13 UTC, baidala commented on app/src/main/java/com/example/movieslibrary/FavoriteMoviesFragment.kt
> +            favorites.removeAt(position)
так лучше не делать. если вы работаете через интерфейс IFavoritesMoviesRepository тогда вся реализация должна быть скрыта. передавайте   favoritesMoviesRepository.removeFromFavorites(movie, position) и в репозитории уже изменяйте список

2021-02-10 00:07 UTC, cat-in-magic-hat commented on app/src/main/java/com/example/movieslibrary/MainActivity.kt
> +            finish()
поправила

2021-02-10 00:12 UTC, cat-in-magic-hat commented on app/src/main/java/com/example/movieslibrary/FavoriteMoviesFragment.kt
> +            favorites.removeAt(position)
идея была в том, что репозиторий хранит все понравившиеся фильмы, адаптер может в общем случае использовать только часть (например, отфильтрованную по определенному признаку) или же применять различные порядки сортировки, т.е. целью было - разделить ответственности за хранение и за обработку между разными классами.
Если этот вариант не ок, а смешивать все так же не хочется, то как лучше поступить?

2021-02-10 18:54 UTC, baidala commented on app/src/main/java/com/example/movieslibrary/FavoriteMoviesFragment.kt
> +            favorites.removeAt(position)
у вас же репозиторий - синглтон. вы можете во фрагменте напрямую (без передачи инстанса через конструктор)  обращаться к методам  FavoritesMoviesRepository.removeFromFavorites(movie).  
в методе removeFromFavorites(itemForRemoving: Movie)  тоже выполняется удаление из этого же списка - один метод выполняеться без необходимости дважды. 
адаптер должен принимать данные и отображать по определенному признаку. если из пришедшего списка надо чтото удалить - это делает не адаптер. в адаптер можно передать listener (interface) методы которого будут вызываться когда нужно удалить фильм из списка.  listener может быть фрагмент и он вызывает метод из репозитория  removeFromFavorites(itemForRemoving: Movie) потом запрашивает новый список и передает его в адаптер для отображения. в таком случае у вас одно место с гарантировано актуальными данными - репозиторий.

2021-02-13 09:03 UTC, merged